name: unit_converter
description: A library to easily convert between units of different system. 
version: 1.0.0+1
homepage: https://github.com/arabbani/unit_converter
author: Arif Rabbani <arif.93rabbani@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
